version: "3.8"

services:
  server:
    build:
      context: server/
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}

  client:
    build:
      context: client/
    ports:
      - "3000:3000"
  db:
    image: postgres:15
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tj
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: goodtube
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
