version: "3.8"

services:
  server:
    build:
      context: server/
    ports:
      - "8080:8080"

  client:
    stop_grace_period: 500ms
    build:
      context: client/
      dockerfile: local.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/app:/usr/share/nginx/html:ro
