version: "3.8"

services:
  server:
    build:
      context: server/
    ports:
      - "8080:8080"

  client:
    stop_grace_period: 500ms
    build:
      context: client/
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app # Live reloading for all served files
