version: "3.8"

services:
  backend:
    build:
      context: ./backend/
    ports:
      - "8080:8080"

  frontend:
    stop_grace_period: 500ms
    build:
      context: ./frontend/
    ports:
      - "3000:3000"
